### ISSUE TITLE
This library is nowhere near the spec

### ISSUE THREAD

**Issue by asimlqt** [tudvari/docker-composer#6]
How do you output the following yaml?

```
version: '3'
services:
  webapp:
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        buildno: 1
```

It was taken from [https://docs.docker.com/compose/compose-file/#build ](https://docs.docker.com/compose/compose-file/#build )
